// ─────────────────────────────────────────────────────────────────────────────
//  icpaste.com — Excel Export
//  Uses SheetJS (xlsx) — zero server needed, runs entirely client-side.
//
//  Columns exported:
//  MPN | Description | Requested Qty | Buy Qty | Adj | Unit Price | Total | Distributor | Link
// ─────────────────────────────────────────────────────────────────────────────

import * as XLSX from "xlsx";
import { OptimizedResult } from "../types";

interface ExportOptions {
  results:      OptimizedResult[];
  currency:     string;
  totalBom:     number;
  prodQty?:     number;       // se in modalità production run
  searchedAt?:  string;
}

export function exportToExcel({
  results,
  currency,
  totalBom,
  prodQty = 1,
  searchedAt,
}: ExportOptions) {

  // ── 1. Costruisci le righe dati ───────────────────────────────────────────
  const rows = results.map(r => {
    const isOk = !r.error;
    const adj  = r.adjustment && r.adjustment !== "none"
      ? r.adjustment === "package"   ? "PKG"
      : r.adjustment === "pricestep" ? "STEP"
      : "PKG+STEP"
      : "";

    return {
      "MPN":              r.mpn,
      "Description":      r.description || "",
      "Requested Qty":    r.requestedQty,
      ...(prodQty > 1 ? { "BOM Qty (×1)": Math.round(r.requestedQty / prodQty) } : {}),
      "Buy Qty":          isOk ? r.optimalQty : "",
      "Adjustment":       adj,
      [`Unit Price (${currency})`]: isOk ? r.unitPrice  : "",
      [`Total (${currency})`]:      isOk ? r.totalPrice : "",
      "Distributor":      isOk ? r.distributor : "—",
      "Buy Link":         isOk ? r.productUrl  : "",
      "Status":           r.error ?? "OK",
    };
  });

  // ── 2. Riga totale ────────────────────────────────────────────────────────
  const totalRow: Record<string, string | number> = {
    "MPN":         "",
    "Description": "",
    "Requested Qty": "",
    "Buy Qty":     "",
    "Adjustment":  "",
    [`Unit Price (${currency})`]: "",
    [`Total (${currency})`]:      totalBom,
    "Distributor": "TOTAL",
    "Buy Link":    "",
    "Status":      "",
  };
  if (prodQty > 1) totalRow["BOM Qty (×1)"] = "";

  // ── 3. Crea worksheet ─────────────────────────────────────────────────────
  const ws = XLSX.utils.json_to_sheet([...rows, {}, totalRow]);

  // ── 4. Larghezze colonne ──────────────────────────────────────────────────
  ws["!cols"] = [
    { wch: 22 },  // MPN
    { wch: 36 },  // Description
    { wch: 14 },  // Requested Qty
    ...(prodQty > 1 ? [{ wch: 14 }] : []),  // BOM Qty (×1)
    { wch: 10 },  // Buy Qty
    { wch: 10 },  // Adjustment
    { wch: 16 },  // Unit Price
    { wch: 14 },  // Total
    { wch: 18 },  // Distributor
    { wch: 60 },  // Buy Link
    { wch: 24 },  // Status
  ];

  // ── 5. Stile header (grassetto) ───────────────────────────────────────────
  const range = XLSX.utils.decode_range(ws["!ref"] ?? "A1");
  for (let col = range.s.c; col <= range.e.c; col++) {
    const cellAddr = XLSX.utils.encode_cell({ r: 0, c: col });
    if (!ws[cellAddr]) continue;
    ws[cellAddr].s = {
      font:      { bold: true, color: { rgb: "FFFFFF" } },
      fill:      { fgColor: { rgb: "0EA5E9" } },
      alignment: { horizontal: "center" },
    };
  }

  // ── 6. Stile riga totale ──────────────────────────────────────────────────
  const totalRowIdx = rows.length + 2; // +1 header, +1 riga vuota
  for (let col = range.s.c; col <= range.e.c; col++) {
    const cellAddr = XLSX.utils.encode_cell({ r: totalRowIdx, c: col });
    if (!ws[cellAddr]) continue;
    ws[cellAddr].s = {
      font: { bold: true },
      fill: { fgColor: { rgb: "F0F9FF" } },
    };
  }

  // ── 7. Crea workbook con metadata ─────────────────────────────────────────
  const wb = XLSX.utils.book_new();
  wb.Props = {
    Title:   "icpaste BOM Export",
    Subject: prodQty > 1 ? `Production Run × ${prodQty}` : "BOM Price Search",
    Author:  "icpaste.com",
    CreatedDate: searchedAt ? new Date(searchedAt) : new Date(),
  };

  XLSX.utils.book_append_sheet(wb, ws, "BOM");

  // ── 8. Secondo foglio: riepilogo ──────────────────────────────────────────
  const summaryData = [
    { "Field": "Generated by",    "Value": "icpaste.com" },
    { "Field": "Date",            "Value": searchedAt ? new Date(searchedAt).toLocaleString() : new Date().toLocaleString() },
    { "Field": "Components",      "Value": results.length },
    { "Field": "Found",           "Value": results.filter(r => !r.error).length },
    { "Field": "Not found",       "Value": results.filter(r => r.error).length },
    { "Field": "BOM Total",       "Value": `${currency} ${totalBom.toFixed(2)}` },
    ...(prodQty > 1 ? [
      { "Field": "Production Run",  "Value": `× ${prodQty} units` },
      { "Field": "Cost per unit",   "Value": `${currency} ${(totalBom / prodQty).toFixed(2)}` },
    ] : []),
  ];

  const wsSummary = XLSX.utils.json_to_sheet(summaryData);
  wsSummary["!cols"] = [{ wch: 20 }, { wch: 30 }];
  XLSX.utils.book_append_sheet(wb, wsSummary, "Summary");

  // ── 9. Download ───────────────────────────────────────────────────────────
  const date     = new Date().toISOString().split("T")[0];
  const prodSuffix = prodQty > 1 ? `_x${prodQty}` : "";
  const fileName = `icpaste_BOM_${date}${prodSuffix}.xlsx`;

  XLSX.writeFile(wb, fileName);
}
